### ISSUE TITLE
Close and comment just posted as comment

### ISSUE THREAD

**Issue by jacwah** [Zomis/Duga#100]
> [Cardshifter/Cardshifter] jacwah commented on issue #297: Including the right file

http://chat.stackexchange.com/transcript/message/23688861#23688861

On Gihub, it's possible to both leave a comment and close the issue in one action. It seems like Duga doesn't pick up on this, and only reports on the comment having been made.

She should do one of these things:
- Post two separate messages, one for the comment, and one for the close.
- Post a message like "jacwah closed and commented on issue..."

**Comment by Zomis** [comment]
This is usually because of a concurrency issue with the database, as both issue comments and issues closed are saved, and GitHub sends two webhook requests to Duga for this.

**Comment by Zomis** [comment]
Fixed since I don't know when
