### ISSUE TITLE
"Possible answer invalidation" has too many false positives

### ISSUE THREAD

**Issue by retailcoder** [Zomis/Duga#103]
Duga seems to link to every single edit to any answered question.

She needs to be pickier than that if she wants to claim *possible answer invalidation* - otherwise the message could be a notch less alarming if changed to *post-answer edit*.

But I like the idea of picking up *possible answer invalidation* edits. The tool just needs a little fine-tuning, to ignore edits where no code is involved.

**Comment by Zomis** [comment]
There are two problems here that I can see:

- Simple `backtick code stuff` is included in the check for whether or not code was changed, see revision 6 at http://codereview.stackexchange.com/posts/17758/revisions
- Intendation changes, see revision 10 at http://codereview.stackexchange.com/posts/3668/revisions

**Comment by Zomis** [comment]
https://github.com/Zomis/Duga/commit/09bfb4bdcdf8c3cdb240a75a9f3383d314b87761 and other recent commits should have fixed this
