### ISSUE TITLE
Decoding the message

### ISSUE THREAD

**Issue by retailcoder** [Zomis/Duga#104]
I love the update that shows who edited who's post! The only thing is that the output is HTML (?) encoded:

>     possible answer invalidation by Mat&#39;s Mug on question by Dan Jones: codereview.stackexchange.com/…

[meta-tag:bug][tag:answer-invalidation][tag:chat-output]

**Comment by Zomis** [comment]
This is what is received from Stack Exchange API:

      "user": {
        "reputation": 40229,
        "user_id": 23788,
        "user_type": "moderator",
        "profile_image": "https://i.stack.imgur.com/2p89X.png?s=128&g=1",
        "display_name": "Mat&#39;s Mug",
        "link": "http://codereview.stackexchange.com/users/23788/mats-mug"
      },

So indeed, Duga doesn't decode the HTML.

See http://stackoverflow.com/q/22820188/1310566 for a possible solution.
