### ISSUE TITLE
Countdown till Winterbash

### ISSUE THREAD

**Issue by SirPython** [Zomis/Duga#116]
Now, it's a little last minute (well, last 7 minutes to be exact), but it would be for Duga to give a countdown until Winterbash officially started.

If not a countdown, maybe the days left until WB is over, etc.

Chat ref: http://chat.stackexchange.com/transcript/message/26144695#26144695

**Comment by Zomis** [comment]
As evidenced by the chat transcript, the community does just as a good job at this than a bot would do (maybe the community does it even better). Won't fix. Not worth it. Would be more spammish than useful.
