### ISSUE TITLE
HTML encoding of answer invalidation reports is halfway done

### ISSUE THREAD

**Issue by retailcoder** [Zomis/Duga#119]
The author of the edit looks ok, but the author of the question doesn't:

    possible answer invalidation by Mat's Mug on question by Mat&#39;s Mug: codereview.stackexchange.com/…

Should be an easy fix :smile:

**Comment by skiwi2** [comment]
Looking at https://github.com/Zomis/Duga/blob/6abe2d4369f7e2dad34a73d6a4d12ed92f643498/src/main/groovy/net/zomis/duga/tasks/qscan/AnswerInvalidationCheck.groovy it seems like `op` only needs to be wrapped into `formatDisplayName`.
