### ISSUE TITLE
Error when running two webhooks to different rooms

### ISSUE THREAD

**Issue by skiwi2** [Zomis/Duga#120]
Because it is not possible (as far as I know?) to post commits from one repository to two different SE rooms, I decided to add two webhooks to a single repository.

However sometimes the message doesn't appear in either of the rooms.

In this case one of the webhooks failed with the following:

**Headers**

> Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: close
Content-Language: en-US
Content-Length: 2985
Content-Type: text/html;charset=UTF-8
Date: Fri, 05 Feb 2016 12:55:38 GMT
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
X-Application-Context: application
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

**Body**

> <html>
	<head>
		<title>Grails Runtime Exception</title>
		
        
        <meta name="layout" content="main">
        <link rel="stylesheet" href="/GithubHookSEChatService/assets/errors-081f1b7cc86c9f8824107b7756baa1cd.css"/>
    
	</head>
	<body>
		
        
            
                <h1>Error 500: Internal Server Error</h1>
<dl class="error-details">
<dt>URI</dt><dd>/GithubHookSEChatService/hooks/github/payload</dd>
<dt>Class</dt><dd>org.hibernate.StaleObjectStateException</dd><dt>Message</dt><dd>null</dd><dt>Caused by</dt><dd>Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [net.zomis.duga.DailyInfo#92]</dd></dl><h2>Trace</h2><pre class="stack">    Line | Method
-&gt;&gt; 1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    617 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

Caused by HibernateOptimisticLockingFailureException: Object of class [net.zomis.duga.DailyInfo] with identifier [92]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [net.zomis.duga.DailyInfo#92]
-&gt;&gt;   33 | $tt__addCommit in net.zomis.duga.DugaStats
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     93 | doInTransaction in grails.transaction.GrailsTransactionTemplate$2
|     90 | execute . in grails.transaction.GrailsTransactionTemplate
|    317 | doCall    in net.zomis.duga.HookStringification$_push_closure1
|   1249 | forEach . in java.util.ArrayList
|    315 | push      in net.zomis.duga.HookStringification
|    345 | postGithub in     &#39;&#39;
|     27 | hook      in net.zomis.duga.GithubHookController
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

Caused by StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [net.zomis.duga.DailyInfo#92]
-&gt;&gt;   33 | $tt__addCommit in net.zomis.duga.DugaStats
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     93 | doInTransaction in grails.transaction.GrailsTransactionTemplate$2
|     90 | execute . in grails.transaction.GrailsTransactionTemplate
|    317 | doCall    in net.zomis.duga.HookStringification$_push_closure1
|   1249 | forEach . in java.util.ArrayList
|    315 | push      in net.zomis.duga.HookStringification
|    345 | postGithub in     &#39;&#39;
|     27 | hook      in net.zomis.duga.GithubHookController
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
</pre>
            
        
    
	</body>
</html>

**Comment by Zomis** [comment]
Ah, right. This makes sense. Whenever Duga gets a commit, she updates the daily statistics for the repository in the database. As you have two commits, there are two queries being made which causes a race condition, which can cause database problems as it does here.

The best fix would be to check if multiple rooms are specified, which would require a change here: https://github.com/Zomis/Duga/blob/develop/grails-app/controllers/net/zomis/duga/GithubHookController.groovy#L29
