### ISSUE TITLE
Feature Request: GitHub Star Races

### ISSUE THREAD

**Issue by retailcoder** [Zomis/Duga#145]
Similar to the "reputation races" feature, would be nice if there was a way to have a "star-racer" parameter on the GitHub web hook, so we could track star races on reload.

For example [Rubberduck](https://github.com/rubberduck-vba/Rubberduck) is currently in a [rather tight race for the top-2 spot](https://github.com/search?o=desc&q=vba&s=stars&type=Repositories) with OleTools.

**Comment by Zomis** [comment]
https://chat.stackexchange.com/transcript/message/56910731#56910731
