### ISSUE TITLE
The project should be split into subprojects

### ISSUE THREAD

**Issue by skiwi2** [Zomis/Duga#2]
This project should be split into two subprojects:
- The StackExchange chat bot
- The hook library

**Comment by Vogel612** [comment]
It's not that new to you guys (especially @Zomis) But the chatbot part exactly matches to scope of https://www.github.com/Vincentyification/JChatExchange Unfortunately there is no release, but latest information from the Java chatroom suggests an alpha build is on his way

**Comment by Zomis** [comment]
Technically, there's a whole bunch of different projects that Duga could be split into, especially with the addition of scanning for comments. However, I don't think this will happen. Maybe one day Duga will use the JChatExchange library as suggested by @Vogel612, if it passes the code review ;)

**Comment by Zomis** [comment]
Re-opening this as this project would benefit of having some parts of it extracted, such as the core chat interactivity (posting to chat and polling chat)

**Comment by Zomis** [comment]
At the moment I feel a bit that the Spring/Grails part should be kept to a minimum and all the other parts extracted to some common Duga project that contains integrations with github and stack-exchange.

**Comment by Zomis** [comment]
duga-core has been an independent part of this project for a while now.
