### ISSUE TITLE
Add support for release events

### ISSUE THREAD

**Issue by skiwi2** [Zomis/Duga#30]
Release events https://developer.github.com/v3/activity/events/types/#releaseevent should be supported.

**Comment by Zomis** [comment]
Tag Events are already supported, does Release events have to be supported as well?

**Comment by Zomis** [comment]
And what is the difference between a release event and a tag added event?

**Comment by ckuhn203** [comment]
A tag can be created without a release, right? I mean, tags are a git thing, while releases are a github thing.

**Comment by retailcoder** [comment]
I didn't know there was a difference, but tags are already sent to the chatroom when they're created - I think it would be *nice to have* them in the daily summary when they occur.

**Comment by Zomis** [comment]
This should be supported by now, as evidenced by http://chat.stackexchange.com/transcript/14929?m=27278645#27278645 . Not sure why I haven't closed this issue before.
