### ISSUE TITLE
Convert #number to an issue link

### ISSUE THREAD

**Issue by Zomis** [Zomis/Duga#40]
When using git and github, it is possible to refer to an issue in a commit message, an issue description/comment, etc. by writing #number, it would be nice if the bot could convert these numbers to links, just like github does.

**Comment by Zomis** [comment]
This is a tricky one, considering that multi-line messages in SE chat are not formatted.

**Comment by ckuhn203** [comment]
I could take or leave this one. I already have a link to the issue that is referring to the other issue. I can just navigate there once I'm on GitHub. It's unlikely that I'd want to go to the referenced issue before reading the entirety of the current one. This is a "nice to have" in my opinion.
