### ISSUE TITLE
Specify user mappings in a better way

### ISSUE THREAD

**Issue by skiwi2** [Zomis/Duga#46]
Currently the user mappings are specified in the following way:

> env.userMappings = skiwi2 -> skiwi, Zomis -> SimonAndréForsberg, janosgyerik -> janos

This should be done in a much nicer way, such that we can actually supply key value pairs via the settings. Perhaps even add them at runtime if possible.

**Comment by Zomis** [comment]
this can be done better when #52 is implemented. I will work on this
