### ISSUE TITLE
a repository not grouped together in daily update

### ISSUE THREAD

**Issue by Zomis** [Zomis/Duga#59]
For some reason, the repository Vogel612/testclient_javabot is showed on two lines in daily update:

[Vogel612/testclient_javabot] 1 closed issue.
[Vogel612/testclient_javabot] 1 commit.

**Comment by Vogel612** [comment]
For reference. The repository has a single registered webhook with the URL: http://stats.zomis.net/GithubHookSEChatService/hooks/github/payload?room=16134

**Comment by Zomis** [comment]
Just a thought that occured right now: This might be because of multi-threading and a race condition.

**Comment by Zomis** [comment]
This is likely because an issue was commented on and closed at the same time.

**Comment by retailcoder** [comment]
For the record, last update of Rubberduck was also on two lines and didn't have any commits... when I'm pretty sure there was about 10

**Comment by Zomis** [comment]
@retailcoder According to the Duga-messages in the [chat transcript](http://chat.stackexchange.com/transcript/14929/2015/4/10) I count the following:

5 comments
2 closed
2 open
2 commits

(Remember that a message like [retailcoder pushed 3 commits to GrammarIsFun](http://chat.stackexchange.com/transcript/message/21017138#21017138) does not count as any commits as the commits had been already done to a previous branch)

Something definitely happened with the counting, which is likely caused by this issue with a comment and issue-closing not being grouped together.

**Comment by retailcoder** [comment]
I noticed at one point it wasn't posting my commits... the memory issue?

Sent from my Samsung mobile

**Comment by Zomis** [comment]
Could be, yes, or caused by some temporary communication problem between github and my server. My internet is not known for being the most reliable at all times.

**Comment by retailcoder** [comment]
Ok, I'll try to commit in 14,400 bauds next time... ... :smiley:

Sent from my Samsung mobile
