### ISSUE TITLE
Out of memory - possible memory leak

### ISSUE THREAD

**Issue by Zomis** [Zomis/Duga#60]
Recently the Tomcat server is running out of memory. I believe this started to happen quite recently, possibly with either the Github API requests or the StackExchange API requests, or with the refactoring of the daily updates. Either way, try to locate this bug.

**Comment by skiwi2** [comment]
Do you have a clue what the date or commit is when this issue started happening?

**Comment by Zomis** [comment]
It was definitely working at the beginning of 2015. I think it started happening in the middle of January. It can possibly be related to when I switched from Windows to Linux. I noticed yesterday that the whole machine is going low on memory when this issue occurs.

Somewhere between 6161c9b715c99f368fb56056fdaa275bacc7a1d4 and 3d928442576761c87487ff08cca9cdde2427925d is what I am sure of.

**Comment by skiwi2** [comment]
Does the amount of RAM used by this application increase steadily over time?

**Comment by skiwi2** [comment]
Do you also have an example of a stack trace that the OOME left behind?

While the cause is not necessarily in that specific method, it could still give some hints.

**Comment by Zomis** [comment]
I'll have to investigate about the RAM. I am not sure about that.

There is no stack trace, unfortunately.

**Comment by Zomis** [comment]
This *might* have been fixed. The bot has survived for more than one day so far. Leaving issue open for a little longer in case it is not fixed.

**Comment by Zomis** [comment]
This is *not* fixed. It is confirmed to not be because of the comment scanning though.

**Comment by Zomis** [comment]
Duga has been up and running now for ten days without the need to restart her. http://chat.stackexchange.com/transcript/20298?m=21702930#21702930
