### ISSUE TITLE
One-liner commit messages

### ISSUE THREAD

**Issue by Zomis** [Zomis/Duga#79]
Sometimes you would like to inform someone that you have made a commit and what that commit contains, so you want to copy the link to only one message and paste in another chat.

Currently each commit causes two chat messages, for example:

1. `[Zomis/Calculator] Zomis pushed commit 1b78c459 to master`
2. `added support for random parenthesis`

I'd like to see something like this instead:

    [Zomis/Calculator] Zomis pushed commit 1b78c459 to master: added support for random parenthesis

Feedback appreciated.

**Comment by ckuhn203** [comment]
:+1: I like it. A lot, but I think #75 might be a prerequisite.
