### ISSUE TITLE
Multi-line commit messages being shown badly as single-line in chat

### ISSUE THREAD

**Issue by Zomis** [Zomis/Duga#80]
With #79 now implemented, if you make a multi-line git commit message, it shows up very badly in chat. For example, see http://chat.stackexchange.com/transcript/message/21313123#21313123

Two options for fixing that I can think of:

1. Strip all new-line characters from commit message when posting in chat.
2. Post multi-line commit messages as multi-line

**Comment by Phrancis** [comment]
Could you fix this with a simple regex to remove new-line characters?

**Comment by Zomis** [comment]
I think this has been fixed recently.
