### ISSUE TITLE
Feature Request: Appveyor Webhook support

### ISSUE THREAD

**Issue by ckuhn203** [Zomis/Duga#85]
I'll admit it. I know next to nothing about webhooks and how they work, but I see that you support Travis webhooks. AppVeyor also exposes webhooks. Any chance Duga could support AppVeyor in the future?

**Comment by Zomis** [comment]
I assume it's something that you use for a certain Rubberduck? If so, and if it turns out that supporting it is not too complicated (which it usually isn't), then yes, absolutely Duga could support it

**Comment by ckuhn203** [comment]
Yes, we recently started using it for Rubberduck. It's a continuous integration service much like Travis. I'm just looking to get a notification in chat when a build completes.

**Comment by ckuhn203** [comment]
[AppVeyor's Webhook Documentation][1] details the json format of the data.

I'm thinking of a message something along the following lines. (I'm not sure what you did for Travis CI, but I'm sure what you've done there would be practically the same.

> [repositoryName] author "Build#" buildVersion status

Or a more concrete example.

> [rubberduck-vba/Rubberduck] ckuhn203 Build# 1.3.19-next Success

Doubly cool if the build number could link to the build via the build url in the json data.

[1]: http://www.appveyor.com/docs/notifications#webhook-payload

**Comment by ckuhn203** [comment]
Thank you @Zomis!
