### ISSUE TITLE
Usernames in ISO8859-1 vs UTF-8

### ISSUE THREAD

**Issue by Zomis** [Zomis/Duga#91]
In the users table the username is currently stored with utf-8. Store as ISO8859-1 instead.

**Comment by Vogel612** [comment]
Doesn't SE handle usernames in UTF-8?? I'm very surprised ...

**Comment by Zomis** [comment]
@Vogel612 SE send usernames in UTF-8 yes, but currently if I would tell Duga to ping me, she doesn't write my proper username, because of my 'é', and because of the spaces in my username.

**Comment by Zomis** [comment]
Solved by not using a database anymore
