### ISSUE TITLE
HTTP 500 when opening pull request

### ISSUE THREAD

**Issue by Vannevelj** [Zomis/Duga#95]
See JSON + stacktrace below

**Comment by Zomis** [comment]
Could you provide the JSON request that was sent to Duga for this? Should be available in the github webhook settings (you'll just need to find the right ones)

**Comment by Vannevelj** [comment]
Request Headers:

	Request URL: http://stats.zomis.net/GithubHookSEChatService/hook?roomId=26639
	Request method: POST
	content-type: application/json
	Expect: 
	User-Agent: GitHub-Hookshot/4963429
	X-GitHub-Delivery: 01753300-45c5-11e5-8dfb-2a2b9f7ec5a9
	X-GitHub-Event: pull_request

Request Payload:

	{
	"action": "opened",
	"number": 177,
	"pull_request": {
		"url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls/177",
		"id": 42718413,
		"html_url": "https://github.com/Vannevelj/VSDiagnostics/pull/177",
		"diff_url": "https://github.com/Vannevelj/VSDiagnostics/pull/177.diff",
		"patch_url": "https://github.com/Vannevelj/VSDiagnostics/pull/177.patch",
		"issue_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/177",
		"number": 177,
		"state": "open",
		"locked": false,
		"title": "Prevent all interface members from having access modifier added.",
		"user": {
		"login": "Hosch250",
		"id": 6299719,
		"avatar_url": "https://avatars.githubusercontent.com/u/6299719?v=3",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Hosch250",
		"html_url": "https://github.com/Hosch250",
		"followers_url": "https://api.github.com/users/Hosch250/followers",
		"following_url": "https://api.github.com/users/Hosch250/following{/other_user}",
		"gists_url": "https://api.github.com/users/Hosch250/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Hosch250/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Hosch250/subscriptions",
		"organizations_url": "https://api.github.com/users/Hosch250/orgs",
		"repos_url": "https://api.github.com/users/Hosch250/repos",
		"events_url": "https://api.github.com/users/Hosch250/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Hosch250/received_events",
		"type": "User",
		"site_admin": false
		},
		"body": "Closes #169 ",
		"created_at": "2015-08-18T16:20:14Z",
		"updated_at": "2015-08-18T16:20:14Z",
		"closed_at": null,
		"merged_at": null,
		"merge_commit_sha": "6edb6bc9b2c7b86a40c41ac2d164fad1b5d2e4a1",
		"assignee": null,
		"milestone": null,
		"commits_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls/177/commits",
		"review_comments_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls/177/comments",
		"review_comment_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls/comments{/number}",
		"comments_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/177/comments",
		"statuses_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/statuses/e3c249b0097cc7635742db1b06202ac59aa5a00e",
		"head": {
		"label": "Hosch250:master",
		"ref": "master",
		"sha": "e3c249b0097cc7635742db1b06202ac59aa5a00e",
		"user": {
			"login": "Hosch250",
			"id": 6299719,
			"avatar_url": "https://avatars.githubusercontent.com/u/6299719?v=3",
			"gravatar_id": "",
			"url": "https://api.github.com/users/Hosch250",
			"html_url": "https://github.com/Hosch250",
			"followers_url": "https://api.github.com/users/Hosch250/followers",
			"following_url": "https://api.github.com/users/Hosch250/following{/other_user}",
			"gists_url": "https://api.github.com/users/Hosch250/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/Hosch250/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/Hosch250/subscriptions",
			"organizations_url": "https://api.github.com/users/Hosch250/orgs",
			"repos_url": "https://api.github.com/users/Hosch250/repos",
			"events_url": "https://api.github.com/users/Hosch250/events{/privacy}",
			"received_events_url": "https://api.github.com/users/Hosch250/received_events",
			"type": "User",
			"site_admin": false
		},
		"repo": {
			"id": 40224079,
			"name": "VSDiagnostics",
			"full_name": "Hosch250/VSDiagnostics",
			"owner": {
			"login": "Hosch250",
			"id": 6299719,
			"avatar_url": "https://avatars.githubusercontent.com/u/6299719?v=3",
			"gravatar_id": "",
			"url": "https://api.github.com/users/Hosch250",
			"html_url": "https://github.com/Hosch250",
			"followers_url": "https://api.github.com/users/Hosch250/followers",
			"following_url": "https://api.github.com/users/Hosch250/following{/other_user}",
			"gists_url": "https://api.github.com/users/Hosch250/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/Hosch250/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/Hosch250/subscriptions",
			"organizations_url": "https://api.github.com/users/Hosch250/orgs",
			"repos_url": "https://api.github.com/users/Hosch250/repos",
			"events_url": "https://api.github.com/users/Hosch250/events{/privacy}",
			"received_events_url": "https://api.github.com/users/Hosch250/received_events",
			"type": "User",
			"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/Hosch250/VSDiagnostics",
			"description": "A collection of code-quality analyzers",
			"fork": true,
			"url": "https://api.github.com/repos/Hosch250/VSDiagnostics",
			"forks_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/forks",
			"keys_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/teams",
			"hooks_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/hooks",
			"issue_events_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/issues/events{/number}",
			"events_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/events",
			"assignees_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/assignees{/user}",
			"branches_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/branches{/branch}",
			"tags_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/tags",
			"blobs_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/languages",
			"stargazers_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/stargazers",
			"contributors_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/contributors",
			"subscribers_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/subscribers",
			"subscription_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/subscription",
			"commits_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/contents/{+path}",
			"compare_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/merges",
			"archive_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/downloads",
			"issues_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/issues{/number}",
			"pulls_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/labels{/name}",
			"releases_url": "https://api.github.com/repos/Hosch250/VSDiagnostics/releases{/id}",
			"created_at": "2015-08-05T04:22:50Z",
			"updated_at": "2015-08-05T04:23:09Z",
			"pushed_at": "2015-08-18T16:16:28Z",
			"git_url": "git://github.com/Hosch250/VSDiagnostics.git",
			"ssh_url": "git@github.com:Hosch250/VSDiagnostics.git",
			"clone_url": "https://github.com/Hosch250/VSDiagnostics.git",
			"svn_url": "https://github.com/Hosch250/VSDiagnostics",
			"homepage": null,
			"size": 842,
			"stargazers_count": 1,
			"watchers_count": 1,
			"language": "C#",
			"has_issues": false,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"open_issues_count": 0,
			"forks": 0,
			"open_issues": 0,
			"watchers": 1,
			"default_branch": "master"
		}
		},
		"base": {
		"label": "Vannevelj:develop",
		"ref": "develop",
		"sha": "3c88877322f18cac0a9e99839529c4a59f19aece",
		"user": {
			"login": "Vannevelj",
			"id": 2777107,
			"avatar_url": "https://avatars.githubusercontent.com/u/2777107?v=3",
			"gravatar_id": "",
			"url": "https://api.github.com/users/Vannevelj",
			"html_url": "https://github.com/Vannevelj",
			"followers_url": "https://api.github.com/users/Vannevelj/followers",
			"following_url": "https://api.github.com/users/Vannevelj/following{/other_user}",
			"gists_url": "https://api.github.com/users/Vannevelj/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/Vannevelj/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/Vannevelj/subscriptions",
			"organizations_url": "https://api.github.com/users/Vannevelj/orgs",
			"repos_url": "https://api.github.com/users/Vannevelj/repos",
			"events_url": "https://api.github.com/users/Vannevelj/events{/privacy}",
			"received_events_url": "https://api.github.com/users/Vannevelj/received_events",
			"type": "User",
			"site_admin": false
		},
		"repo": {
			"id": 34992631,
			"name": "VSDiagnostics",
			"full_name": "Vannevelj/VSDiagnostics",
			"owner": {
			"login": "Vannevelj",
			"id": 2777107,
			"avatar_url": "https://avatars.githubusercontent.com/u/2777107?v=3",
			"gravatar_id": "",
			"url": "https://api.github.com/users/Vannevelj",
			"html_url": "https://github.com/Vannevelj",
			"followers_url": "https://api.github.com/users/Vannevelj/followers",
			"following_url": "https://api.github.com/users/Vannevelj/following{/other_user}",
			"gists_url": "https://api.github.com/users/Vannevelj/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/Vannevelj/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/Vannevelj/subscriptions",
			"organizations_url": "https://api.github.com/users/Vannevelj/orgs",
			"repos_url": "https://api.github.com/users/Vannevelj/repos",
			"events_url": "https://api.github.com/users/Vannevelj/events{/privacy}",
			"received_events_url": "https://api.github.com/users/Vannevelj/received_events",
			"type": "User",
			"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/Vannevelj/VSDiagnostics",
			"description": "A collection of code-quality analyzers",
			"fork": false,
			"url": "https://api.github.com/repos/Vannevelj/VSDiagnostics",
			"forks_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/forks",
			"keys_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/teams",
			"hooks_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/hooks",
			"issue_events_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/events{/number}",
			"events_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/events",
			"assignees_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/assignees{/user}",
			"branches_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/branches{/branch}",
			"tags_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/tags",
			"blobs_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/languages",
			"stargazers_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/stargazers",
			"contributors_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/contributors",
			"subscribers_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/subscribers",
			"subscription_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/subscription",
			"commits_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/contents/{+path}",
			"compare_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/merges",
			"archive_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/downloads",
			"issues_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues{/number}",
			"pulls_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/labels{/name}",
			"releases_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/releases{/id}",
			"created_at": "2015-05-03T16:33:02Z",
			"updated_at": "2015-07-17T21:31:08Z",
			"pushed_at": "2015-08-18T16:20:14Z",
			"git_url": "git://github.com/Vannevelj/VSDiagnostics.git",
			"ssh_url": "git@github.com:Vannevelj/VSDiagnostics.git",
			"clone_url": "https://github.com/Vannevelj/VSDiagnostics.git",
			"svn_url": "https://github.com/Vannevelj/VSDiagnostics",
			"homepage": null,
			"size": 1492,
			"stargazers_count": 20,
			"watchers_count": 20,
			"language": "C#",
			"has_issues": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 7,
			"mirror_url": null,
			"open_issues_count": 40,
			"forks": 7,
			"open_issues": 40,
			"watchers": 20,
			"default_branch": "master"
		}
		},
		"_links": {
		"self": {
			"href": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls/177"
		},
		"html": {
			"href": "https://github.com/Vannevelj/VSDiagnostics/pull/177"
		},
		"issue": {
			"href": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/177"
		},
		"comments": {
			"href": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/177/comments"
		},
		"review_comments": {
			"href": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls/177/comments"
		},
		"review_comment": {
			"href": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls/comments{/number}"
		},
		"commits": {
			"href": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls/177/commits"
		},
		"statuses": {
			"href": "https://api.github.com/repos/Vannevelj/VSDiagnostics/statuses/e3c249b0097cc7635742db1b06202ac59aa5a00e"
		}
		},
		"merged": false,
		"mergeable": true,
		"mergeable_state": "clean",
		"merged_by": null,
		"comments": 0,
		"review_comments": 0,
		"commits": 1,
		"additions": 43,
		"deletions": 3,
		"changed_files": 2
	},
	"repository": {
		"id": 34992631,
		"name": "VSDiagnostics",
		"full_name": "Vannevelj/VSDiagnostics",
		"owner": {
		"login": "Vannevelj",
		"id": 2777107,
		"avatar_url": "https://avatars.githubusercontent.com/u/2777107?v=3",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Vannevelj",
		"html_url": "https://github.com/Vannevelj",
		"followers_url": "https://api.github.com/users/Vannevelj/followers",
		"following_url": "https://api.github.com/users/Vannevelj/following{/other_user}",
		"gists_url": "https://api.github.com/users/Vannevelj/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Vannevelj/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Vannevelj/subscriptions",
		"organizations_url": "https://api.github.com/users/Vannevelj/orgs",
		"repos_url": "https://api.github.com/users/Vannevelj/repos",
		"events_url": "https://api.github.com/users/Vannevelj/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Vannevelj/received_events",
		"type": "User",
		"site_admin": false
		},
		"private": false,
		"html_url": "https://github.com/Vannevelj/VSDiagnostics",
		"description": "A collection of code-quality analyzers",
		"fork": false,
		"url": "https://api.github.com/repos/Vannevelj/VSDiagnostics",
		"forks_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/forks",
		"keys_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/keys{/key_id}",
		"collaborators_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/collaborators{/collaborator}",
		"teams_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/teams",
		"hooks_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/hooks",
		"issue_events_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/events{/number}",
		"events_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/events",
		"assignees_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/assignees{/user}",
		"branches_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/branches{/branch}",
		"tags_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/tags",
		"blobs_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/blobs{/sha}",
		"git_tags_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/tags{/sha}",
		"git_refs_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/refs{/sha}",
		"trees_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/trees{/sha}",
		"statuses_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/statuses/{sha}",
		"languages_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/languages",
		"stargazers_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/stargazers",
		"contributors_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/contributors",
		"subscribers_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/subscribers",
		"subscription_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/subscription",
		"commits_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/commits{/sha}",
		"git_commits_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/commits{/sha}",
		"comments_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/comments{/number}",
		"issue_comment_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/comments{/number}",
		"contents_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/contents/{+path}",
		"compare_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/compare/{base}...{head}",
		"merges_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/merges",
		"archive_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/{archive_format}{/ref}",
		"downloads_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/downloads",
		"issues_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues{/number}",
		"pulls_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls{/number}",
		"milestones_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/milestones{/number}",
		"notifications_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/notifications{?since,all,participating}",
		"labels_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/labels{/name}",
		"releases_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/releases{/id}",
		"created_at": "2015-05-03T16:33:02Z",
		"updated_at": "2015-07-17T21:31:08Z",
		"pushed_at": "2015-08-18T16:20:14Z",
		"git_url": "git://github.com/Vannevelj/VSDiagnostics.git",
		"ssh_url": "git@github.com:Vannevelj/VSDiagnostics.git",
		"clone_url": "https://github.com/Vannevelj/VSDiagnostics.git",
		"svn_url": "https://github.com/Vannevelj/VSDiagnostics",
		"homepage": null,
		"size": 1492,
		"stargazers_count": 20,
		"watchers_count": 20,
		"language": "C#",
		"has_issues": true,
		"has_downloads": true,
		"has_wiki": true,
		"has_pages": false,
		"forks_count": 7,
		"mirror_url": null,
		"open_issues_count": 40,
		"forks": 7,
		"open_issues": 40,
		"watchers": 20,
		"default_branch": "master"
	},
	"sender": {
		"login": "Hosch250",
		"id": 6299719,
		"avatar_url": "https://avatars.githubusercontent.com/u/6299719?v=3",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Hosch250",
		"html_url": "https://github.com/Hosch250",
		"followers_url": "https://api.github.com/users/Hosch250/followers",
		"following_url": "https://api.github.com/users/Hosch250/following{/other_user}",
		"gists_url": "https://api.github.com/users/Hosch250/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Hosch250/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Hosch250/subscriptions",
		"organizations_url": "https://api.github.com/users/Hosch250/orgs",
		"repos_url": "https://api.github.com/users/Hosch250/repos",
		"events_url": "https://api.github.com/users/Hosch250/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Hosch250/received_events",
		"type": "User",
		"site_admin": false
	}
	}

Response Headers:

	Cache-Control: no-cache, no-store, max-age=0, must-revalidate
	Connection: close
	Content-Language: en-US
	Content-Type: text/html;charset=UTF-8
	Date: Tue, 18 Aug 2015 16:20:15 GMT
	Expires: 0
	Pragma: no-cache
	Server: Apache-Coyote/1.1
	Transfer-Encoding: chunked
	X-Application-Context: application
	X-Content-Type-Options: nosniff
	X-Frame-Options: DENY
	X-XSS-Protection: 1; mode=block

Response Body:

	<html>
		<head>
			<title>Grails Runtime Exception</title>
			
			
			<meta name="layout" content="main">
			<link rel="stylesheet" href="/GithubHookSEChatService/assets/errors-081f1b7cc86c9f8824107b7756baa1cd.css"/>
		
		</head>
		<body>
			
			
				
					<h1>Error 500: Internal Server Error</h1>
	<dl class="error-details">
	<dt>URI</dt><dd>/GithubHookSEChatService/hook</dd>
	<dt>Class</dt><dd>groovy.lang.MissingPropertyException</dd><dt>Message</dt><dd>null</dd><dt>Caused by</dt><dd>No such property: list for class: net.zomis.duga.HookStringification
	Possible solutions: class</dd></dl><h2>Trace</h2><pre class="stack">    Line | Method
	-&gt;&gt; 1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
	|    617 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
	^    745 | run . . . in java.lang.Thread
	
	Caused by MissingPropertyException: No such property: list for class: net.zomis.duga.HookStringification
	Possible solutions: class
	-&gt;&gt;  235 | pull_request in net.zomis.duga.HookStringification
	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
	|    334 | postGithub in     &#39;&#39;
	|     27 | hook . .  in net.zomis.duga.GithubHookController
	|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
	|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
	^    745 | run       in java.lang.Thread
	</pre>
				
			
		
		</body>
	</html>

**Comment by Zomis** [comment]
The chat message is about a build event, the provided JSON request is about a pull-request event. Please provide the JSON request that caused that particular chat message.

(And please add a new issue for that Internal Server Error message for that particular pull request JSON data there...)
