### ISSUE TITLE
Non-mergeable pull request has an empty build url

### ISSUE THREAD

**Issue by Vannevelj** [Zomis/Duga#97]
I'm not sure what happened [here](http://chat.stackexchange.com/transcript/message/23501459#23501459) but the markup was suddenly messed up when creating a link:

> [Vannevelj/VSDiagnostics] `[build]()` for commit 5f4c34cc on ???: AppVeyor was unable to build non-mergeable pull request

Request Header:

	Request URL: http://stats.zomis.net/GithubHookSEChatService/hook?roomId=26639
	Request method: POST
	content-type: application/json
	Expect: 
	User-Agent: GitHub-Hookshot/4963429
	X-GitHub-Delivery: 2cac5200-45c6-11e5-9c27-76750921cc70
	X-GitHub-Event: status

Request Payload:

	{
	"id": 287781781,
	"sha": "5f4c34ccd3c508a16b49df825eaec2b8d3bd22c3",
	"name": "Vannevelj/VSDiagnostics",
	"target_url": "",
	"context": "continuous-integration/appveyor",
	"description": "AppVeyor was unable to build non-mergeable pull request",
	"state": "failure",
	"commit": {
		"sha": "5f4c34ccd3c508a16b49df825eaec2b8d3bd22c3",
		"commit": {
		"author": {
			"name": "Hosch250",
			"email": "hosch250@live.com",
			"date": "2015-08-18T16:26:53Z"
		},
		"committer": {
			"name": "Hosch250",
			"email": "hosch250@live.com",
			"date": "2015-08-18T16:26:53Z"
		},
		"message": "Remove unnecessary \"async\" operator.",
		"tree": {
			"sha": "64eb93654c8fd114dc5f6cbce858a8b1ad68f4ac",
			"url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/trees/64eb93654c8fd114dc5f6cbce858a8b1ad68f4ac"
		},
		"url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/commits/5f4c34ccd3c508a16b49df825eaec2b8d3bd22c3",
		"comment_count": 0
		},
		"url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/commits/5f4c34ccd3c508a16b49df825eaec2b8d3bd22c3",
		"html_url": "https://github.com/Vannevelj/VSDiagnostics/commit/5f4c34ccd3c508a16b49df825eaec2b8d3bd22c3",
		"comments_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/commits/5f4c34ccd3c508a16b49df825eaec2b8d3bd22c3/comments",
		"author": {
		"login": "Hosch250",
		"id": 6299719,
		"avatar_url": "https://avatars.githubusercontent.com/u/6299719?v=3",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Hosch250",
		"html_url": "https://github.com/Hosch250",
		"followers_url": "https://api.github.com/users/Hosch250/followers",
		"following_url": "https://api.github.com/users/Hosch250/following{/other_user}",
		"gists_url": "https://api.github.com/users/Hosch250/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Hosch250/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Hosch250/subscriptions",
		"organizations_url": "https://api.github.com/users/Hosch250/orgs",
		"repos_url": "https://api.github.com/users/Hosch250/repos",
		"events_url": "https://api.github.com/users/Hosch250/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Hosch250/received_events",
		"type": "User",
		"site_admin": false
		},
		"committer": {
		"login": "Hosch250",
		"id": 6299719,
		"avatar_url": "https://avatars.githubusercontent.com/u/6299719?v=3",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Hosch250",
		"html_url": "https://github.com/Hosch250",
		"followers_url": "https://api.github.com/users/Hosch250/followers",
		"following_url": "https://api.github.com/users/Hosch250/following{/other_user}",
		"gists_url": "https://api.github.com/users/Hosch250/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Hosch250/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Hosch250/subscriptions",
		"organizations_url": "https://api.github.com/users/Hosch250/orgs",
		"repos_url": "https://api.github.com/users/Hosch250/repos",
		"events_url": "https://api.github.com/users/Hosch250/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Hosch250/received_events",
		"type": "User",
		"site_admin": false
		},
		"parents": [
		{
			"sha": "e3c249b0097cc7635742db1b06202ac59aa5a00e",
			"url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/commits/e3c249b0097cc7635742db1b06202ac59aa5a00e",
			"html_url": "https://github.com/Vannevelj/VSDiagnostics/commit/e3c249b0097cc7635742db1b06202ac59aa5a00e"
		}
		]
	},
	"branches": [
	
	],
	"created_at": "2015-08-18T16:28:36Z",
	"updated_at": "2015-08-18T16:28:36Z",
	"repository": {
		"id": 34992631,
		"name": "VSDiagnostics",
		"full_name": "Vannevelj/VSDiagnostics",
		"owner": {
		"login": "Vannevelj",
		"id": 2777107,
		"avatar_url": "https://avatars.githubusercontent.com/u/2777107?v=3",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Vannevelj",
		"html_url": "https://github.com/Vannevelj",
		"followers_url": "https://api.github.com/users/Vannevelj/followers",
		"following_url": "https://api.github.com/users/Vannevelj/following{/other_user}",
		"gists_url": "https://api.github.com/users/Vannevelj/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Vannevelj/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Vannevelj/subscriptions",
		"organizations_url": "https://api.github.com/users/Vannevelj/orgs",
		"repos_url": "https://api.github.com/users/Vannevelj/repos",
		"events_url": "https://api.github.com/users/Vannevelj/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Vannevelj/received_events",
		"type": "User",
		"site_admin": false
		},
		"private": false,
		"html_url": "https://github.com/Vannevelj/VSDiagnostics",
		"description": "A collection of code-quality analyzers",
		"fork": false,
		"url": "https://api.github.com/repos/Vannevelj/VSDiagnostics",
		"forks_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/forks",
		"keys_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/keys{/key_id}",
		"collaborators_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/collaborators{/collaborator}",
		"teams_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/teams",
		"hooks_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/hooks",
		"issue_events_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/events{/number}",
		"events_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/events",
		"assignees_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/assignees{/user}",
		"branches_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/branches{/branch}",
		"tags_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/tags",
		"blobs_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/blobs{/sha}",
		"git_tags_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/tags{/sha}",
		"git_refs_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/refs{/sha}",
		"trees_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/trees{/sha}",
		"statuses_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/statuses/{sha}",
		"languages_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/languages",
		"stargazers_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/stargazers",
		"contributors_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/contributors",
		"subscribers_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/subscribers",
		"subscription_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/subscription",
		"commits_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/commits{/sha}",
		"git_commits_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/git/commits{/sha}",
		"comments_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/comments{/number}",
		"issue_comment_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues/comments{/number}",
		"contents_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/contents/{+path}",
		"compare_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/compare/{base}...{head}",
		"merges_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/merges",
		"archive_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/{archive_format}{/ref}",
		"downloads_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/downloads",
		"issues_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/issues{/number}",
		"pulls_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/pulls{/number}",
		"milestones_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/milestones{/number}",
		"notifications_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/notifications{?since,all,participating}",
		"labels_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/labels{/name}",
		"releases_url": "https://api.github.com/repos/Vannevelj/VSDiagnostics/releases{/id}",
		"created_at": "2015-05-03T16:33:02Z",
		"updated_at": "2015-07-17T21:31:08Z",
		"pushed_at": "2015-08-18T16:28:33Z",
		"git_url": "git://github.com/Vannevelj/VSDiagnostics.git",
		"ssh_url": "git@github.com:Vannevelj/VSDiagnostics.git",
		"clone_url": "https://github.com/Vannevelj/VSDiagnostics.git",
		"svn_url": "https://github.com/Vannevelj/VSDiagnostics",
		"homepage": null,
		"size": 1492,
		"stargazers_count": 20,
		"watchers_count": 20,
		"language": "C#",
		"has_issues": true,
		"has_downloads": true,
		"has_wiki": true,
		"has_pages": false,
		"forks_count": 7,
		"mirror_url": null,
		"open_issues_count": 42,
		"forks": 7,
		"open_issues": 42,
		"watchers": 20,
		"default_branch": "master"
	},
	"sender": {
		"login": "Vannevelj",
		"id": 2777107,
		"avatar_url": "https://avatars.githubusercontent.com/u/2777107?v=3",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Vannevelj",
		"html_url": "https://github.com/Vannevelj",
		"followers_url": "https://api.github.com/users/Vannevelj/followers",
		"following_url": "https://api.github.com/users/Vannevelj/following{/other_user}",
		"gists_url": "https://api.github.com/users/Vannevelj/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Vannevelj/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Vannevelj/subscriptions",
		"organizations_url": "https://api.github.com/users/Vannevelj/orgs",
		"repos_url": "https://api.github.com/users/Vannevelj/repos",
		"events_url": "https://api.github.com/users/Vannevelj/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Vannevelj/received_events",
		"type": "User",
		"site_admin": false
	}
	}

**Comment by Zomis** [comment]
I guess the only reasonable course of action is to check if `"target_url"` is empty or not and if it is, just show this:

[Vannevelj/VSDiagnostics] build for commit 5f4c34cc on ???: AppVeyor was unable to build non-mergeable pull request

**Comment by Vannevelj** [comment]
That makes sense.
