### ISSUE TITLE
Only posting Github comment of PR

### ISSUE THREAD

**Issue by jacwah** [Zomis/Duga#99]
> The SPDX identifier for the Apache 2.0 license is AFL-2.0.

[Duga just turned into a trivia bot.](http://chat.stackexchange.com/transcript/message/23616058#23616058)

This message was posted when I created [a PR](https://github.com/Cardshifter/HTML-Client/pull/64) from my fork of https://github.com/Cardshifter/HTML-Client.

**Comment by Zomis** [comment]
related to #95

**Comment by Zomis** [comment]
Here's some data for a PR that causes the problem, for testing:

    {
      "action": "opened",
      "number": 98,
      "pull_request": {
        "url": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls/98",
        "id": 44860520,
        "html_url": "https://github.com/Cardshifter/HTML-Client/pull/98",
        "diff_url": "https://github.com/Cardshifter/HTML-Client/pull/98.diff",
        "patch_url": "https://github.com/Cardshifter/HTML-Client/pull/98.patch",
        "issue_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/98",
        "number": 98,
        "state": "open",
        "locked": false,
        "title": "Develop",
        "user": {
          "login": "SirPython",
          "id": 8549957,
          "avatar_url": "https://avatars.githubusercontent.com/u/8549957?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/SirPython",
          "html_url": "https://github.com/SirPython",
          "followers_url": "https://api.github.com/users/SirPython/followers",
          "following_url": "https://api.github.com/users/SirPython/following{/other_user}",
          "gists_url": "https://api.github.com/users/SirPython/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/SirPython/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/SirPython/subscriptions",
          "organizations_url": "https://api.github.com/users/SirPython/orgs",
          "repos_url": "https://api.github.com/users/SirPython/repos",
          "events_url": "https://api.github.com/users/SirPython/events{/privacy}",
          "received_events_url": "https://api.github.com/users/SirPython/received_events",
          "type": "User",
          "site_admin": false
        },
        "body": "updating deploy-script",
        "created_at": "2015-09-12T20:26:15Z",
        "updated_at": "2015-09-12T20:26:15Z",
        "closed_at": null,
        "merged_at": null,
        "merge_commit_sha": "e0c23d160efd52fb4fc40e09e1e63ed0c23c4d70",
        "assignee": null,
        "milestone": null,
        "commits_url": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls/98/commits",
        "review_comments_url": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls/98/comments",
        "review_comment_url": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/98/comments",
        "statuses_url": "https://api.github.com/repos/Cardshifter/HTML-Client/statuses/3664d72df8644f95a9e17da7fde63c0fce0c4e97",
        "head": {
          "label": "Cardshifter:develop",
          "ref": "develop",
          "sha": "3664d72df8644f95a9e17da7fde63c0fce0c4e97",
          "user": {
            "login": "Cardshifter",
            "id": 8478053,
            "avatar_url": "https://avatars.githubusercontent.com/u/8478053?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Cardshifter",
            "html_url": "https://github.com/Cardshifter",
            "followers_url": "https://api.github.com/users/Cardshifter/followers",
            "following_url": "https://api.github.com/users/Cardshifter/following{/other_user}",
            "gists_url": "https://api.github.com/users/Cardshifter/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Cardshifter/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Cardshifter/subscriptions",
            "organizations_url": "https://api.github.com/users/Cardshifter/orgs",
            "repos_url": "https://api.github.com/users/Cardshifter/repos",
            "events_url": "https://api.github.com/users/Cardshifter/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Cardshifter/received_events",
            "type": "Organization",
            "site_admin": false
          },
          "repo": {
            "id": 39746630,
            "name": "HTML-Client",
            "full_name": "Cardshifter/HTML-Client",
            "owner": {
              "login": "Cardshifter",
              "id": 8478053,
              "avatar_url": "https://avatars.githubusercontent.com/u/8478053?v=3",
              "gravatar_id": "",
              "url": "https://api.github.com/users/Cardshifter",
              "html_url": "https://github.com/Cardshifter",
              "followers_url": "https://api.github.com/users/Cardshifter/followers",
              "following_url": "https://api.github.com/users/Cardshifter/following{/other_user}",
              "gists_url": "https://api.github.com/users/Cardshifter/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/Cardshifter/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/Cardshifter/subscriptions",
              "organizations_url": "https://api.github.com/users/Cardshifter/orgs",
              "repos_url": "https://api.github.com/users/Cardshifter/repos",
              "events_url": "https://api.github.com/users/Cardshifter/events{/privacy}",
              "received_events_url": "https://api.github.com/users/Cardshifter/received_events",
              "type": "Organization",
              "site_admin": false
            },
            "private": false,
            "html_url": "https://github.com/Cardshifter/HTML-Client",
            "description": "HTML/CSS/JS-based client for Cardshifter",
            "fork": false,
            "url": "https://api.github.com/repos/Cardshifter/HTML-Client",
            "forks_url": "https://api.github.com/repos/Cardshifter/HTML-Client/forks",
            "keys_url": "https://api.github.com/repos/Cardshifter/HTML-Client/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/Cardshifter/HTML-Client/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/Cardshifter/HTML-Client/teams",
            "hooks_url": "https://api.github.com/repos/Cardshifter/HTML-Client/hooks",
            "issue_events_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/events{/number}",
            "events_url": "https://api.github.com/repos/Cardshifter/HTML-Client/events",
            "assignees_url": "https://api.github.com/repos/Cardshifter/HTML-Client/assignees{/user}",
            "branches_url": "https://api.github.com/repos/Cardshifter/HTML-Client/branches{/branch}",
            "tags_url": "https://api.github.com/repos/Cardshifter/HTML-Client/tags",
            "blobs_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/Cardshifter/HTML-Client/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/Cardshifter/HTML-Client/languages",
            "stargazers_url": "https://api.github.com/repos/Cardshifter/HTML-Client/stargazers",
            "contributors_url": "https://api.github.com/repos/Cardshifter/HTML-Client/contributors",
            "subscribers_url": "https://api.github.com/repos/Cardshifter/HTML-Client/subscribers",
            "subscription_url": "https://api.github.com/repos/Cardshifter/HTML-Client/subscription",
            "commits_url": "https://api.github.com/repos/Cardshifter/HTML-Client/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/Cardshifter/HTML-Client/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/Cardshifter/HTML-Client/contents/{+path}",
            "compare_url": "https://api.github.com/repos/Cardshifter/HTML-Client/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/Cardshifter/HTML-Client/merges",
            "archive_url": "https://api.github.com/repos/Cardshifter/HTML-Client/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/Cardshifter/HTML-Client/downloads",
            "issues_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues{/number}",
            "pulls_url": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/Cardshifter/HTML-Client/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/Cardshifter/HTML-Client/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/Cardshifter/HTML-Client/labels{/name}",
            "releases_url": "https://api.github.com/repos/Cardshifter/HTML-Client/releases{/id}",
            "created_at": "2015-07-26T23:54:19Z",
            "updated_at": "2015-08-26T11:26:18Z",
            "pushed_at": "2015-09-12T20:26:16Z",
            "git_url": "git://github.com/Cardshifter/HTML-Client.git",
            "ssh_url": "git@github.com:Cardshifter/HTML-Client.git",
            "clone_url": "https://github.com/Cardshifter/HTML-Client.git",
            "svn_url": "https://github.com/Cardshifter/HTML-Client",
            "homepage": null,
            "size": 9219,
            "stargazers_count": 6,
            "watchers_count": 6,
            "language": "JavaScript",
            "has_issues": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 3,
            "mirror_url": null,
            "open_issues_count": 38,
            "forks": 3,
            "open_issues": 38,
            "watchers": 6,
            "default_branch": "master"
          }
        },
        "base": {
          "label": "Cardshifter:deploy-script",
          "ref": "deploy-script",
          "sha": "6591d23429859cd4b6c6106ac2b06ae8885abd0a",
          "user": {
            "login": "Cardshifter",
            "id": 8478053,
            "avatar_url": "https://avatars.githubusercontent.com/u/8478053?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Cardshifter",
            "html_url": "https://github.com/Cardshifter",
            "followers_url": "https://api.github.com/users/Cardshifter/followers",
            "following_url": "https://api.github.com/users/Cardshifter/following{/other_user}",
            "gists_url": "https://api.github.com/users/Cardshifter/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Cardshifter/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Cardshifter/subscriptions",
            "organizations_url": "https://api.github.com/users/Cardshifter/orgs",
            "repos_url": "https://api.github.com/users/Cardshifter/repos",
            "events_url": "https://api.github.com/users/Cardshifter/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Cardshifter/received_events",
            "type": "Organization",
            "site_admin": false
          },
          "repo": {
            "id": 39746630,
            "name": "HTML-Client",
            "full_name": "Cardshifter/HTML-Client",
            "owner": {
              "login": "Cardshifter",
              "id": 8478053,
              "avatar_url": "https://avatars.githubusercontent.com/u/8478053?v=3",
              "gravatar_id": "",
              "url": "https://api.github.com/users/Cardshifter",
              "html_url": "https://github.com/Cardshifter",
              "followers_url": "https://api.github.com/users/Cardshifter/followers",
              "following_url": "https://api.github.com/users/Cardshifter/following{/other_user}",
              "gists_url": "https://api.github.com/users/Cardshifter/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/Cardshifter/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/Cardshifter/subscriptions",
              "organizations_url": "https://api.github.com/users/Cardshifter/orgs",
              "repos_url": "https://api.github.com/users/Cardshifter/repos",
              "events_url": "https://api.github.com/users/Cardshifter/events{/privacy}",
              "received_events_url": "https://api.github.com/users/Cardshifter/received_events",
              "type": "Organization",
              "site_admin": false
            },
            "private": false,
            "html_url": "https://github.com/Cardshifter/HTML-Client",
            "description": "HTML/CSS/JS-based client for Cardshifter",
            "fork": false,
            "url": "https://api.github.com/repos/Cardshifter/HTML-Client",
            "forks_url": "https://api.github.com/repos/Cardshifter/HTML-Client/forks",
            "keys_url": "https://api.github.com/repos/Cardshifter/HTML-Client/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/Cardshifter/HTML-Client/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/Cardshifter/HTML-Client/teams",
            "hooks_url": "https://api.github.com/repos/Cardshifter/HTML-Client/hooks",
            "issue_events_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/events{/number}",
            "events_url": "https://api.github.com/repos/Cardshifter/HTML-Client/events",
            "assignees_url": "https://api.github.com/repos/Cardshifter/HTML-Client/assignees{/user}",
            "branches_url": "https://api.github.com/repos/Cardshifter/HTML-Client/branches{/branch}",
            "tags_url": "https://api.github.com/repos/Cardshifter/HTML-Client/tags",
            "blobs_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/Cardshifter/HTML-Client/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/Cardshifter/HTML-Client/languages",
            "stargazers_url": "https://api.github.com/repos/Cardshifter/HTML-Client/stargazers",
            "contributors_url": "https://api.github.com/repos/Cardshifter/HTML-Client/contributors",
            "subscribers_url": "https://api.github.com/repos/Cardshifter/HTML-Client/subscribers",
            "subscription_url": "https://api.github.com/repos/Cardshifter/HTML-Client/subscription",
            "commits_url": "https://api.github.com/repos/Cardshifter/HTML-Client/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/Cardshifter/HTML-Client/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/Cardshifter/HTML-Client/contents/{+path}",
            "compare_url": "https://api.github.com/repos/Cardshifter/HTML-Client/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/Cardshifter/HTML-Client/merges",
            "archive_url": "https://api.github.com/repos/Cardshifter/HTML-Client/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/Cardshifter/HTML-Client/downloads",
            "issues_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues{/number}",
            "pulls_url": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/Cardshifter/HTML-Client/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/Cardshifter/HTML-Client/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/Cardshifter/HTML-Client/labels{/name}",
            "releases_url": "https://api.github.com/repos/Cardshifter/HTML-Client/releases{/id}",
            "created_at": "2015-07-26T23:54:19Z",
            "updated_at": "2015-08-26T11:26:18Z",
            "pushed_at": "2015-09-12T20:26:16Z",
            "git_url": "git://github.com/Cardshifter/HTML-Client.git",
            "ssh_url": "git@github.com:Cardshifter/HTML-Client.git",
            "clone_url": "https://github.com/Cardshifter/HTML-Client.git",
            "svn_url": "https://github.com/Cardshifter/HTML-Client",
            "homepage": null,
            "size": 9219,
            "stargazers_count": 6,
            "watchers_count": 6,
            "language": "JavaScript",
            "has_issues": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 3,
            "mirror_url": null,
            "open_issues_count": 38,
            "forks": 3,
            "open_issues": 38,
            "watchers": 6,
            "default_branch": "master"
          }
        },
        "_links": {
          "self": {
            "href": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls/98"
          },
          "html": {
            "href": "https://github.com/Cardshifter/HTML-Client/pull/98"
          },
          "issue": {
            "href": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/98"
          },
          "comments": {
            "href": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/98/comments"
          },
          "review_comments": {
            "href": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls/98/comments"
          },
          "review_comment": {
            "href": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls/comments{/number}"
          },
          "commits": {
            "href": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls/98/commits"
          },
          "statuses": {
            "href": "https://api.github.com/repos/Cardshifter/HTML-Client/statuses/3664d72df8644f95a9e17da7fde63c0fce0c4e97"
          }
        },
        "merged": false,
        "mergeable": true,
        "mergeable_state": "clean",
        "merged_by": null,
        "comments": 0,
        "review_comments": 0,
        "commits": 7,
        "additions": 0,
        "deletions": 0,
        "changed_files": 78
      },
      "repository": {
        "id": 39746630,
        "name": "HTML-Client",
        "full_name": "Cardshifter/HTML-Client",
        "owner": {
          "login": "Cardshifter",
          "id": 8478053,
          "avatar_url": "https://avatars.githubusercontent.com/u/8478053?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Cardshifter",
          "html_url": "https://github.com/Cardshifter",
          "followers_url": "https://api.github.com/users/Cardshifter/followers",
          "following_url": "https://api.github.com/users/Cardshifter/following{/other_user}",
          "gists_url": "https://api.github.com/users/Cardshifter/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Cardshifter/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Cardshifter/subscriptions",
          "organizations_url": "https://api.github.com/users/Cardshifter/orgs",
          "repos_url": "https://api.github.com/users/Cardshifter/repos",
          "events_url": "https://api.github.com/users/Cardshifter/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Cardshifter/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/Cardshifter/HTML-Client",
        "description": "HTML/CSS/JS-based client for Cardshifter",
        "fork": false,
        "url": "https://api.github.com/repos/Cardshifter/HTML-Client",
        "forks_url": "https://api.github.com/repos/Cardshifter/HTML-Client/forks",
        "keys_url": "https://api.github.com/repos/Cardshifter/HTML-Client/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Cardshifter/HTML-Client/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Cardshifter/HTML-Client/teams",
        "hooks_url": "https://api.github.com/repos/Cardshifter/HTML-Client/hooks",
        "issue_events_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Cardshifter/HTML-Client/events",
        "assignees_url": "https://api.github.com/repos/Cardshifter/HTML-Client/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Cardshifter/HTML-Client/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Cardshifter/HTML-Client/tags",
        "blobs_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Cardshifter/HTML-Client/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Cardshifter/HTML-Client/languages",
        "stargazers_url": "https://api.github.com/repos/Cardshifter/HTML-Client/stargazers",
        "contributors_url": "https://api.github.com/repos/Cardshifter/HTML-Client/contributors",
        "subscribers_url": "https://api.github.com/repos/Cardshifter/HTML-Client/subscribers",
        "subscription_url": "https://api.github.com/repos/Cardshifter/HTML-Client/subscription",
        "commits_url": "https://api.github.com/repos/Cardshifter/HTML-Client/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Cardshifter/HTML-Client/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Cardshifter/HTML-Client/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Cardshifter/HTML-Client/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Cardshifter/HTML-Client/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Cardshifter/HTML-Client/merges",
        "archive_url": "https://api.github.com/repos/Cardshifter/HTML-Client/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Cardshifter/HTML-Client/downloads",
        "issues_url": "https://api.github.com/repos/Cardshifter/HTML-Client/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Cardshifter/HTML-Client/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Cardshifter/HTML-Client/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Cardshifter/HTML-Client/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Cardshifter/HTML-Client/labels{/name}",
        "releases_url": "https://api.github.com/repos/Cardshifter/HTML-Client/releases{/id}",
        "created_at": "2015-07-26T23:54:19Z",
        "updated_at": "2015-08-26T11:26:18Z",
        "pushed_at": "2015-09-12T20:26:16Z",
        "git_url": "git://github.com/Cardshifter/HTML-Client.git",
        "ssh_url": "git@github.com:Cardshifter/HTML-Client.git",
        "clone_url": "https://github.com/Cardshifter/HTML-Client.git",
        "svn_url": "https://github.com/Cardshifter/HTML-Client",
        "homepage": null,
        "size": 9219,
        "stargazers_count": 6,
        "watchers_count": 6,
        "language": "JavaScript",
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 3,
        "mirror_url": null,
        "open_issues_count": 38,
        "forks": 3,
        "open_issues": 38,
        "watchers": 6,
        "default_branch": "master"
      },
      "organization": {
        "login": "Cardshifter",
        "id": 8478053,
        "url": "https://api.github.com/orgs/Cardshifter",
        "repos_url": "https://api.github.com/orgs/Cardshifter/repos",
        "events_url": "https://api.github.com/orgs/Cardshifter/events",
        "members_url": "https://api.github.com/orgs/Cardshifter/members{/member}",
        "public_members_url": "https://api.github.com/orgs/Cardshifter/public_members{/member}",
        "avatar_url": "https://avatars.githubusercontent.com/u/8478053?v=3",
        "description": null
      },
      "sender": {
        "login": "SirPython",
        "id": 8549957,
        "avatar_url": "https://avatars.githubusercontent.com/u/8549957?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/SirPython",
        "html_url": "https://github.com/SirPython",
        "followers_url": "https://api.github.com/users/SirPython/followers",
        "following_url": "https://api.github.com/users/SirPython/following{/other_user}",
        "gists_url": "https://api.github.com/users/SirPython/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/SirPython/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/SirPython/subscriptions",
        "organizations_url": "https://api.github.com/users/SirPython/orgs",
        "repos_url": "https://api.github.com/users/SirPython/repos",
        "events_url": "https://api.github.com/users/SirPython/events{/privacy}",
        "received_events_url": "https://api.github.com/users/SirPython/received_events",
        "type": "User",
        "site_admin": false
      }
    }
